// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantReservation.Db;

#nullable disable

namespace RestaurantReservation.Db.Migrations
{
    [DbContext(typeof(RestaurantReservationDbContext))]
    [Migration("20251020082736_seedingdata")]
    partial class seedingdata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RestaurantReservation.Db.Customer", b =>
                {
                    b.Property<int>("customer_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("customer_id"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone_number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("customer_id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            customer_id = 1,
                            email = "john.doe@example.com",
                            first_name = "John",
                            last_name = "Doe",
                            phone_number = "111-222-3333"
                        },
                        new
                        {
                            customer_id = 2,
                            email = "jane.smith@example.com",
                            first_name = "Jane",
                            last_name = "Smith",
                            phone_number = "222-333-4444"
                        },
                        new
                        {
                            customer_id = 3,
                            email = "peter.jones@example.com",
                            first_name = "Peter",
                            last_name = "Jones",
                            phone_number = "333-444-5555"
                        },
                        new
                        {
                            customer_id = 4,
                            email = "mary.williams@example.com",
                            first_name = "Mary",
                            last_name = "Williams",
                            phone_number = "444-555-6666"
                        },
                        new
                        {
                            customer_id = 5,
                            email = "david.brown@example.com",
                            first_name = "David",
                            last_name = "Brown",
                            phone_number = "555-666-7777"
                        });
                });

            modelBuilder.Entity("RestaurantReservation.Db.Employee", b =>
                {
                    b.Property<int>("employee_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("employee_id"));

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("restaurant_id")
                        .HasColumnType("int");

                    b.HasKey("employee_id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            employee_id = 1,
                            first_name = "Alice",
                            last_name = "Johnson",
                            position = "Manager",
                            restaurant_id = 1
                        },
                        new
                        {
                            employee_id = 2,
                            first_name = "Bob",
                            last_name = "Miller",
                            position = "Chef",
                            restaurant_id = 1
                        },
                        new
                        {
                            employee_id = 3,
                            first_name = "Charlie",
                            last_name = "Davis",
                            position = "Manager",
                            restaurant_id = 2
                        },
                        new
                        {
                            employee_id = 4,
                            first_name = "Diana",
                            last_name = "Garcia",
                            position = "Waiter",
                            restaurant_id = 2
                        },
                        new
                        {
                            employee_id = 5,
                            first_name = "Ethan",
                            last_name = "Rodriguez",
                            position = "Manager",
                            restaurant_id = 3
                        });
                });

            modelBuilder.Entity("RestaurantReservation.Db.MenuItem", b =>
                {
                    b.Property<int>("item_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("item_id"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("restaurant_id")
                        .HasColumnType("int");

                    b.HasKey("item_id");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            item_id = 1,
                            description = "Grilled to perfection",
                            name = "Steak",
                            price = 25.50m,
                            restaurant_id = 1
                        },
                        new
                        {
                            item_id = 2,
                            description = "Fresh greens",
                            name = "Salad",
                            price = 12.00m,
                            restaurant_id = 1
                        },
                        new
                        {
                            item_id = 3,
                            description = "Classic Italian",
                            name = "Pasta",
                            price = 18.75m,
                            restaurant_id = 2
                        },
                        new
                        {
                            item_id = 4,
                            description = "Wood-fired",
                            name = "Pizza",
                            price = 20.00m,
                            restaurant_id = 2
                        },
                        new
                        {
                            item_id = 5,
                            description = "Hearty and warm",
                            name = "Soup",
                            price = 9.50m,
                            restaurant_id = 3
                        });
                });

            modelBuilder.Entity("RestaurantReservation.Db.Order", b =>
                {
                    b.Property<int>("order_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("order_id"));

                    b.Property<int>("employee_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("order_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("reservation_id")
                        .HasColumnType("int");

                    b.Property<decimal>("total_amount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("order_id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            order_id = 1,
                            employee_id = 2,
                            order_date = new DateTime(2025, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            reservation_id = 1,
                            total_amount = 50.00m
                        },
                        new
                        {
                            order_id = 2,
                            employee_id = 2,
                            order_date = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            reservation_id = 2,
                            total_amount = 25.00m
                        },
                        new
                        {
                            order_id = 3,
                            employee_id = 4,
                            order_date = new DateTime(2025, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            reservation_id = 3,
                            total_amount = 75.00m
                        },
                        new
                        {
                            order_id = 4,
                            employee_id = 4,
                            order_date = new DateTime(2025, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            reservation_id = 4,
                            total_amount = 40.00m
                        },
                        new
                        {
                            order_id = 5,
                            employee_id = 5,
                            order_date = new DateTime(2025, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            reservation_id = 5,
                            total_amount = 100.00m
                        });
                });

            modelBuilder.Entity("RestaurantReservation.Db.OrderItem", b =>
                {
                    b.Property<int>("order_item_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("order_item_id"));

                    b.Property<int>("item_id")
                        .HasColumnType("int");

                    b.Property<int>("order_id")
                        .HasColumnType("int");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.HasKey("order_item_id");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            order_item_id = 1,
                            item_id = 1,
                            order_id = 1,
                            quantity = 2
                        },
                        new
                        {
                            order_item_id = 2,
                            item_id = 2,
                            order_id = 2,
                            quantity = 1
                        },
                        new
                        {
                            order_item_id = 3,
                            item_id = 3,
                            order_id = 3,
                            quantity = 3
                        },
                        new
                        {
                            order_item_id = 4,
                            item_id = 4,
                            order_id = 4,
                            quantity = 2
                        },
                        new
                        {
                            order_item_id = 5,
                            item_id = 5,
                            order_id = 5,
                            quantity = 4
                        });
                });

            modelBuilder.Entity("RestaurantReservation.Db.Reservation", b =>
                {
                    b.Property<int>("reservation_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("reservation_id"));

                    b.Property<int>("customer_id")
                        .HasColumnType("int");

                    b.Property<int>("party_size")
                        .HasColumnType("int");

                    b.Property<DateTime>("reservation_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("restaurant_id")
                        .HasColumnType("int");

                    b.Property<int>("table_id")
                        .HasColumnType("int");

                    b.HasKey("reservation_id");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            reservation_id = 1,
                            customer_id = 1,
                            party_size = 4,
                            reservation_date = new DateTime(2025, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            restaurant_id = 1,
                            table_id = 1
                        },
                        new
                        {
                            reservation_id = 2,
                            customer_id = 2,
                            party_size = 2,
                            reservation_date = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            restaurant_id = 1,
                            table_id = 2
                        },
                        new
                        {
                            reservation_id = 3,
                            customer_id = 3,
                            party_size = 5,
                            reservation_date = new DateTime(2025, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            restaurant_id = 2,
                            table_id = 3
                        },
                        new
                        {
                            reservation_id = 4,
                            customer_id = 4,
                            party_size = 3,
                            reservation_date = new DateTime(2025, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            restaurant_id = 2,
                            table_id = 4
                        },
                        new
                        {
                            reservation_id = 5,
                            customer_id = 5,
                            party_size = 7,
                            reservation_date = new DateTime(2025, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            restaurant_id = 3,
                            table_id = 5
                        });
                });

            modelBuilder.Entity("RestaurantReservation.Db.Restaurant", b =>
                {
                    b.Property<int>("restaurant_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("restaurant_id"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("opening_hours")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone_number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("restaurant_id");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            restaurant_id = 1,
                            address = "123 Main St",
                            name = "The Golden Spoon",
                            opening_hours = "9 AM - 10 PM",
                            phone_number = "123-456-7890"
                        },
                        new
                        {
                            restaurant_id = 2,
                            address = "456 Oak Ave",
                            name = "The Silver Platter",
                            opening_hours = "10 AM - 11 PM",
                            phone_number = "234-567-8901"
                        },
                        new
                        {
                            restaurant_id = 3,
                            address = "789 Pine Ln",
                            name = "The Bronze Fork",
                            opening_hours = "8 AM - 9 PM",
                            phone_number = "345-678-9012"
                        },
                        new
                        {
                            restaurant_id = 4,
                            address = "101 Maple Dr",
                            name = "The Copper Knife",
                            opening_hours = "11 AM - 12 AM",
                            phone_number = "456-789-0123"
                        },
                        new
                        {
                            restaurant_id = 5,
                            address = "202 Birch Rd",
                            name = "The Iron Skillet",
                            opening_hours = "7 AM - 8 PM",
                            phone_number = "567-890-1234"
                        });
                });

            modelBuilder.Entity("RestaurantReservation.Db.RestaurantTable", b =>
                {
                    b.Property<int>("table_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("table_id"));

                    b.Property<int>("capacity")
                        .HasColumnType("int");

                    b.Property<int>("restaurant_id")
                        .HasColumnType("int");

                    b.HasKey("table_id");

                    b.ToTable("RestaurantTables");

                    b.HasData(
                        new
                        {
                            table_id = 1,
                            capacity = 4,
                            restaurant_id = 1
                        },
                        new
                        {
                            table_id = 2,
                            capacity = 2,
                            restaurant_id = 1
                        },
                        new
                        {
                            table_id = 3,
                            capacity = 6,
                            restaurant_id = 2
                        },
                        new
                        {
                            table_id = 4,
                            capacity = 4,
                            restaurant_id = 2
                        },
                        new
                        {
                            table_id = 5,
                            capacity = 8,
                            restaurant_id = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
